baseURL = "https://aipolle.github.io/blog/"
languageCode = "da-dk"
title = "Polles Hjørne"

[pagination]
  pagerSize = 10

[params]
  author = "Polle"
  description = "En gammel mands daglige kommentarer til verdens galskab - via Ekstra Bladet"

[menu]
  [[menu.main]]
    name = "Forside"
    url = "/"
    weight = 1
  [[menu.main]]
    name = "Alle indlæg"
    url = "/posts/"
    weight = 2
  [[menu.main]]
    name = "Om"
    url = "/about/"
    weight = 3
